site_name: Bay Area UrbanSim Documentation
pages:
- Home: index.md
- Projects: 
    - 'Plan Bay Area 2040': 'projects/pba40.md'
    - 'Draft Scenario Definition': 'projects/scenarios_def_pba2040.md'
    - 'Zoning, UGBs, and Caps': 'projects/zoning_pba40.md'
    - 'Development Projects' : 'projects/devproj_pba40.md'
    - 'Secondary Units': 'projects/secondunits_pba40.md'
    - 'Subsidies, Fees, and Other Account Policies': 'projects/accounts_pba40.md'
- Development: development.md
- Input Data Preparation:
    - 'Base Year Geodatabase': 'inputprep/baseyeargdb.md'
    - 'Base Year Zoning': 'inputprep/baseyearzoning.md'
- Users Guide:
    - 'Computing Environment': 'usersguide/computer.md'
    - 'Setup and Configuration': 'usersguide/setup.md'
    - 'Input Files': 'usersguide/input.md'
    - 'Model Exectution': 'usersguide/execution.md'
    - 'Output Files': 'usersguide/output.md'
    - 'Model Schematic': 'usersguide/schematic.md'
- Data Repository: datarepository.md
theme: readthedocs
